apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://loopin-prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_HOST:-http://localhost:3100}
